[project]
name = "data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc>=3.67.1",
    "evidently>=0.7.21",
    "hydra-core>=1.3.6",
    "interrogate>=1.7.0",
    "kestra>=1.3.0",
    "matplotlib>=3.11.1",
    "mypy>=2.3.1",
    "numpy>=2.4.6",
    "omegaconf>=2.3.1",
    "pandas>=3.0.5",
    "pipe>=2.2",
    "pre-commit>=4.6.2",
    "prefect>=3.8.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
    ".venv",
    "build",
    "dist",
   "*.ipynb",
   "*.md",
    ".mypy_cache",
    ".ruff_cache",
]

[tool.ruff.lint]
extend-select = [
    "E",   # pycodestyle errors (antes flake8)
    "W",   # pycodestyle warnings
    "F",   # pyflakes (antes flake8)
    "I",   # isort — reemplaza a isort como paquete separado
    "UP",  # pyupgrade
    # "D",   # pydocstyle
    "C90", # mccabe complexity (antes flake8 max-complexity)
]
ignore = [
    "D203",  # incompatible con D211 (una en blanco antes de clase)
    "D213",  # incompatible con D212 (resumen en primera línea)
]

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "D104"]
"tests/*" = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 5
exclude = ["setup.py", "docs", "build", ".venv", "notebooks", "tests"]
ignore-regex = ["^get$", "^set$", "^_.*", ".*BaseClass.*"]
verbose = 1
quiet = false
whitelist-regex = []
color = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
exclude = ["notebooks", "build", "dist", "\\.venv"]
warn_return_any = true
warn_unused_configs = true