name: Run code
on:
  push:
    branches:
      - main
    paths:
      - config/**
      - src/**
      - data/**
      - .github/workflows/run_pipeline.yaml

permissions:
  contents: write

jobs:
  run_code:
    name: Run code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository
        id: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Pull data from DVC
        run: |
          uv run dvc remote modify origin --local auth basic
          uv run dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          uv run dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
          uv run dvc pull

      - name: Run the pipeline with DVC
        run: uv run dvc repro

      - name: Push the outcome to DVC remote storage
        run: uv run dvc push

      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: actualizar dvc.lock through automated pipeline [skip ci]"
          branch: main
          file_pattern: dvc.lock